# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

while True:
    
    Nota = int(input("Digite sua Nota: "))

    if Nota <0 or Nota >10:
        print("Valor Inválido")
    else:
        print("Valor válido")